#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

echo "Concourse 'check' metadata"
echo " - Using BUILD_ID: ${BUILD_ID}"
echo " - Using BUILD_NAME: ${BUILD_NAME}"
echo " - Using BUILD_JOB_NAME: ${BUILD_JOB_NAME}"
echo " - Using BUILD_PIPELINE_NAME: ${BUILD_PIPELINE_NAME}"
echo " - Using BUILD_PIPELINE_INSTANCE_VARS: ${BUILD_PIPELINE_INSTANCE_VARS}"
echo " - Using BUILD_TEAM_NAME: ${BUILD_TEAM_NAME}"
echo " - Using ATC_EXTERNAL_URL: ${ATC_EXTERNAL_URL}"

printf "\n"

payload=$(mktemp /tmp/exchange-concourse-resource-artifact.XXXXXX)

cat > $payload <&0

echo "   in - request: $(cat ${payload})"

printf "\n"

export URI=$(jq -r '.source.uri // ""' < $payload)
export CLIENT_ID=$(jq -r '.source.client_id // ""' < $payload)
export CLIENT_SECRET=$(jq -r '.source.client_secret // ""' < $payload)
export MULE_ENV=$(jq -r '.source.mule_env // ""' < $payload)
export ENVIRONMENT_NAME=$(jq -r '.source.environment_name // ""' < $payload)
export GROUP_ID=$(jq -r '.source.group_id // ""' < $payload)
export ARTIFACT_ID=$(jq -r '.source.artifact_id // ""' < $payload)

if [ -z "${URI}" ]; then
  echo "invalid payload (missing uri)"
  exit 1
fi

if [ -z "${CLIENT_ID}" ]; then
  echo "invalid payload (missing client_id)"
  exit 1
fi

if [ -z "${CLIENT_SECRET}" ]; then
  echo "invalid payload (missing client_secret)"
  exit 1
fi

if [ -z "${MULE_ENV}" ]; then
  echo "invalid payload (missing mule_env)"
  exit 1
fi

if [ -z "${ENVIRONMENT_NAME}" ]; then
  echo "invalid payload (missing environment_name)"
  exit 1
fi

if [ -z "${GROUP_ID}" ]; then
  echo "invalid payload (missing group_id)"
  exit 1
fi

if [ -z "${ARTIFACT_ID}" ]; then
  echo "invalid payload (missing artifact_id)"
  exit 1
fi

echo "Runtime Fabric Concourse Resource 'check' settings"
echo " - Using URI: ${URI}"
echo " - Using MULE_ENV: ${MULE_ENV}"
echo " - Using ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}"
echo " - Using GROUP_ID: ${GROUP_ID}"
echo " - Using ARTIFACT_ID: ${ARTIFACT_ID}"

printf "\n"

source $(dirname $0)/api.sh

get_token_for_connected_app "${CLIENT_ID}" "${CLIENT_SECRET}" "${URI}"

printf "\n"

get_application_asset_from_rtf \
    "${URI}" \
    "${MULE_ENV}" \
    "${ENVIRONMENT_NAME}" \
    "${GROUP_ID}" \
    "${ARTIFACT_ID}"
    
out="{ \
  \"version\": { \"ref\": \"${VERSION}\" }, \
  \"metadata\": [ \
    { \"name\": \"group_id\", \"value\": \"${GROUP_ID}\"}, \
    { \"name\": \"artifact_id\", \"value\": \"${ARTIFACT_ID}\" } \
  ] \
}"

echo "  out - response: ${out}"

printf "${out}" >&3
